spring:
  application:
    name: "SOURCES-SERVICE"
  main:
    web-application-type: servlet
  profiles:
    active: prod
  jpa:
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true

furrify:
  limits:
    sources: ${FURRIFY_LIMITS_SOURCES:50000}
    refresh-requests: ${FURRIFY_LIMITS_SOURCES:50000}