logging:
  level:
    web: DEBUG

spring:
  kafka:
    bootstrap-servers: http://192.168.0.200:9092
    schema-registry-servers: http://192.168.0.200:8081
    consumer:
      group-id:
        prefix: "sources-test-"
    producer:
      retries: 3

  datasource:
    driverClassName: org.h2.Driver
    username: 'sa'
    password: 'password'
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

infinispan:
  remote:
    server-list: 192.168.0.200:11222
    client-intelligence: BASIC
    use-auth: true
    auth-user-name: admin
    auth-password: admin
    marshaller: org.infinispan.commons.marshall.ProtoStreamMarshaller

server:
  port: 7074

keycloak:
  auth-server-url: http://192.168.0.200:6565/auth
  realm: dev
  resource: furrifyws-storage
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true
  use-resource-role-mappings: true