logging:
  level:
    web: INFO

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry-servers: ${KAFKA_SCHEMA_REGISTRY_SERVERS}
    consumer:
      group-id:
        prefix: "furrifyws-storage-sources-"
    producer:
      retries: 3

  datasource:
    driverClassName: ${DATABASE_DRIVER}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE}

infinispan:
  remote:
    server-list: ${INFINISPAN_REMOTE_SERVER_LIST}


server:
  port: 8080

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true
  use-resource-role-mappings: true